export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_TYPE = 'SET_MESSAGE_TYPE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PENDING_AXIOS_CALL = 'PENDING_AXIOS_CALL';
export const SET_EXISTING_TAGS = 'SET_EXISTING_TAGS';