# Generated by Django 2.0.5 on 2018-07-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='songtag',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_tags', to='song_manager.Song'),
        ),
        migrations.AlterField(
            model_name='songtag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_tags', to='song_manager.Tag'),
        ),
    ]
